deploymentName: message-deployment
serviceName: message
appLabel: message
appName: message
replicaCount: 1
image:
  repository: kimhakseang/message
  tag: v3
containerPort: 8011
service:
  type: ClusterIP
  port: 8011
  targetPort: 8011
appname_enabled: true
profile_enabled: true
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: true
datasource_enabled: false