deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: kimhakseang/gatewayserver
  tag: v3

containerPort: 8075

service:
  type: LoadBalancer
  port: 8075
  targetPort: 8075

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
postgresql_enabled: false
mongodb_enabled: false