deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver
replicaCount: 1
image:
  repository: kimhakseang/configserver
  tag: v3
containerPort: 8071
service:
  type: ClusterIP
  port: 8071
  targetPort: 8071
appname_enabled: true
profile_enabled: true
config_enabled: false
eureka_enabled: false
resouceserver_enabled: true
otel_enabled: false
kafka_enabled: false
postgresql_enabled: false
mongodb_enabled: false