services:

  com-network:
    mem_limit: 700m
    networks:
      - learn_network

  # com-rabbit:
  #   extends: com-network
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     SPRING_RABBITMQ_HOST: rabbitmq

    
  com-configserver:
    extends: com-network
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none

  com-eurekaserver:
    extends: com-configserver
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILE_ACTIVE: dev
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9000/eureka
  