apiVersion: apps/v1
kind: Deployment  
metadata:
  name: message-deployment
  labels:
    app: message
spec:
  replicas: 2
  # Selector: The service routes traffic to pods with the label app: configserver.
  selector: 
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: kimhakseang/message:v3
        # envFrom:
        #   - configMapRef:
        #       name: kimhakseang-configmap
        env:
          - name: configserver
            value: "optional:configserver:http://configserver:8071/"
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: message
spec:
  selector:
    app: message
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010