apiVersion: apps/v1
# The kind field defines the type of Kubernetes object
kind: Deployment  
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  # Selector: The service routes traffic to pods with the label app: keycloak.
  selector: 
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0.4
        args: ["start-dev"]
        envFrom:
          - configMapRef:
              name: kimhakseang-configmap
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 8080