apiVersion: apps/v1
kind: Deployment  
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  # Selector: The service routes traffic to pods with the label app: configserver.
  selector: 
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: kimhakseang/eurekaserver:v3
        env:
          - name: EUREKA_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: kimhakseang-configmap
                key: EUREKA_APPLICATION_NAME
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: kimhakseang-configmap
                key: SPRING_CONFIG_IMPORT
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000