apiVersion: apps/v1
kind: Deployment  
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 1
  # Selector: The service routes traffic to pods with the label app: configserver.
  selector: 
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: kimhakseang/account:v3
        envFrom:
          - configMapRef:
              name: kimhakseang-configmap
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080