apiVersion: apps/v1
kind: Deployment  
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 1
  # Selector: The service routes traffic to pods with the label app: configserver.
  selector: 
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: kimhakseang/account:v3
        env:
          - name: ACCOUNT_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: kimhakseang-configmap
                key: ACCOUNT_APPLICATION_NAME
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: kimhakseang-configmap
                key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          - name: SPRING_DATA_MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: kimhakseang-configmap
                key: SPRING_DATA_MONGODB_HOST
          - name: SPRING_DATA_MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: kimhakseang-configmap
                key: SPRING_DATA_MONGODB_PORT
          - name: SPRING_DATA_MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: kimhakseang-configmap
                key: SPRING_DATA_MONGODB_DATABASE
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080